### ISSUE TITLE
Prepare data for other categories

### ISSUE THREAD

**Issue by garoff** [TheArtificial/theartificial.nl#39]
Left panel categories should redraw the visualisation
- Structure
- Country 
- Reccurence

~ Prepare new data set?
~ Transition between categories?

**Comment by gerwitz** [comment]
different pre-baked JSON files might do for MVP. If you can figure out how to ensure each node retains the same ID then D3 will even transition smoothly despite re-loading fresh data!

(Because the binding between drawn element and data is done via an ID stored on the drawn element in the DOM. This is why we can just replace-all-the-nodes after filtering them.)

**Comment by garoff** [comment]
**Artist nodes** can share the same **id** in each JSON file.
but **Category nodes** wont share the same **id** because they dont share the same number of nodes. Is it fine if I use different **id** for each category node ?

- category **Industry** has **5** nodes (0 digital, 1 motion, 2 print, 3 product, 4 sound design)
- category **Structure** has **3** nodes ( independant, represented, agency )
- category **Country** has **6** nodes ( africa,  asia,  australia,  europe,  north america,  south america) within which I'd also like to include sub-nodes of countries.
- category **Recurrence** has 3 nodes ( 2015,  2016,  both years)

**Comment by gerwitz** [comment]
I don’t know (or need to know) how you’re generating these JSONs, but since the category nodes represent very different things it’s appropriate if they have completely different IDs.

I suggest giving them IDs like “industry-2” and “country-5” so there is no chance of them overlapping with other nodes.

**Comment by garoff** [comment]
What's the best practice to organise data for the multiple entries filters in the .JSON?
For now it is **"groupcontinent" : "3-4-5"**, is it better to write **"groupcontinent" : "3,4,5"** or to make it three **distincts lines**? 

<img width="210" alt="data-filters-orga" src="https://cloud.githubusercontent.com/assets/11830989/12783324/1d2090fe-ca81-11e5-880b-1ace91aaae6f.png">

**Comment by gerwitz** [comment]
You want to end up with an array of values, so like use `"groupcontinent": [3,4]`
